ldd ch03: scull - WIP
register 3 minor devices

tested as below
- accessing /dev/rust_scull3 did not work because it's not registered
  device
- accessing /dev/rust_scull2 generated unimplemented panic
  as intended

I will add implementation of each file operation.

/ # insmod share/rust_scull.ko
[   20.082543] rust_scull: rust_scull is loaded
/ # cat /proc/modules
rust_scull 16384 0 - Live 0xffffffffc0201000 (E)
/ # cat /proc/devices
Character devices:
  1 mem
  4 /dev/vc/0
  4 tty
  4 ttyS
  5 /dev/tty
  5 /dev/console
  5 /dev/ptmx
  5 ttyprintk
  7 vcs
 10 misc
 13 input
 29 fb
128 ptm
136 pts
244 rust_scull
245 bsg
246 remoteproc
247 ptp
248 pps
249 dma_heap
250 dax
251 dimmctl
252 ndctl
253 tpm
254 gpiochip

Block devices:
  7 loop
254 virtblk
259 blkext
/ # mknod /dev/rust_scull0 c 244 0
/ # mknod /dev/rust_scull1 c 244 1
/ # mknod /dev/rust_scull2 c 244 2
/ # mknod /dev/rust_scull3 c 244 3
/ # cat /dev/rust_scull3
cat: can't open '/dev/rust_scull3': No such device or address
/ # cat /dev/rust_scull1
[  131.790417] rust_kernel: panicked at 'not implemented', samples/rust/rust_scull.rs:51:9
[  131.791845] ------------[ cut here ]------------
[  131.792568] kernel BUG at rust/helpers.c:46!
[  131.793261] invalid opcode: 0000 [#1] PREEMPT SMP NOPTI
[  131.794053] CPU: 0 PID: 135 Comm: cat Tainted: G            E      6.3.0+ #9
[  131.795151] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014
[  131.795739] RIP: 0010:rust_helper_BUG+0x9/0x10
[  131.795739] Code: 00 48 8d 7d d0 48 c7 c6 b0 d8 eb 81 e8 80 b4 45 00 0f 0b 00 00 cc cc 00 00 cc cc 00 00 cc cc 00 00 0f 1f e
[  131.795739] RSP: 0018:ffff888005783b58 EFLAGS: 00010286
[  131.795739] RAX: 000000000000004b RBX: 0000000000000000 RCX: ffffffff82482430
[  131.795739] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000004
[  131.795739] RBP: ffff888005783b58 R08: 0000000000000000 R09: 0000000000000000
[  131.795739] R10: ffff888005783a20 R11: 3fffffffffffffff R12: 00000000fffffffa
[  131.795739] R13: ffff888005712200 R14: ffff888005745d00 R15: ffff888005742388
[  131.795739] FS:  00000000009613c0(0000) GS:ffff888007a00000(0000) knlGS:0000000000000000
[  131.795739] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  131.795739] CR2: 00000000005f7431 CR3: 00000000057a0000 CR4: 00000000000006f0
[  131.795739] Call Trace:
[  131.795739]  <TASK>
[  131.795739]  rust_begin_unwind+0x62/0x80
[  131.795739]  ? _RNvXsP_NtCsgh59pMgT09I_4core3fmtRhNtB5_5Debug3fmtCsfFwfLe9nonL_6kernel+0x50/0x50
[  131.795739]  _RNvNtCsgh59pMgT09I_4core9panicking9panic_fmt+0x2d/0x30
[  131.795739]  _RNvNtCsgh59pMgT09I_4core9panicking5panic+0x44/0x50
[  131.795739]  _RNvMs3_NtCsfFwfLe9nonL_6kernel4fileINtB5_16OperationsVtableINtNtB7_6chrdev12RegistrationKj3_ENtCs1A9u1z2KKij_]
[  131.795739]  chrdev_open+0x1a9/0x1e0
[  131.795739]  ? cd_forget+0x70/0x70
[  131.795739]  do_dentry_open+0x166/0x450
[  131.795739]  vfs_open+0x2d/0x30
[  131.795739]  path_openat+0xa8b/0xc50
[  131.795739]  do_filp_open+0xa1/0x130
[  131.795739]  ? getname_flags+0x50/0x1e0
[  131.795739]  ? alloc_fd+0x146/0x190
[  131.795739]  do_sys_openat2+0x6d/0x130
[  131.795739]  __x64_sys_openat+0x71/0x80
[  131.795739]  do_syscall_64+0x35/0x50
[  131.795739]  entry_SYSCALL_64_after_hwframe+0x63/0xcd
[  131.795739] RIP: 0033:0x4ad15b
[  131.795739] Code: 25 00 00 41 00 3d 00 00 41 00 74 4b 64 8b 04 25 18 00 00 00 85 c0 75 67 44 89 e2 48 89 ee bf 9c ff ff ff 5
[  131.795739] RSP: 002b:00007fff5a30b170 EFLAGS: 00000246 ORIG_RAX: 0000000000000101
[  131.795739] RAX: ffffffffffffffda RBX: 00007fff5a30b4c0 RCX: 00000000004ad15b
[  131.795739] RDX: 0000000000000000 RSI: 00007fff5a30bfbe RDI: 00000000ffffff9c
[  131.795739] RBP: 00007fff5a30bfbe R08: 0000000000000001 R09: 0000000000000000
[  131.795739] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000000
[  131.795739] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000001
[  131.795739]  </TASK>
[  131.795739] Modules linked in: rust_scull(E) [last unloaded: rust_scull(E)]
[  131.830547] ---[ end trace 0000000000000000 ]---
[  131.830843] RIP: 0010:rust_helper_BUG+0x9/0x10
[  131.831140] Code: 00 48 8d 7d d0 48 c7 c6 b0 d8 eb 81 e8 80 b4 45 00 0f 0b 00 00 cc cc 00 00 cc cc 00 00 cc cc 00 00 0f 1f e
[  131.832273] RSP: 0018:ffff888005783b58 EFLAGS: 00010286
[  131.832584] RAX: 000000000000004b RBX: 0000000000000000 RCX: ffffffff82482430
[  131.833023] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000004
[  131.833467] RBP: ffff888005783b58 R08: 0000000000000000 R09: 0000000000000000
[  131.833915] R10: ffff888005783a20 R11: 3fffffffffffffff R12: 00000000fffffffa
[  131.834354] R13: ffff888005712200 R14: ffff888005745d00 R15: ffff888005742388
[  131.834816] FS:  00000000009613c0(0000) GS:ffff888007a00000(0000) knlGS:0000000000000000
[  131.835320] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  131.835677] CR2: 00000000005f7431 CR3: 00000000057a0000 CR4: 00000000000006f0
Segmentation fault